name: Test WebView

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Build Test APK
        shell: cmd
        run: |
          gradle :app:assembleDebug

      - name: Upload Test APK
        uses: actions/upload-artifact@v4
        with:
          name: webview-test
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
